name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Do a full checkout (all branches)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: milliHQ/gh-action-release-branch@v2.0.0
        with:
          release-branch: release
          release-tag: ${{ github.event.inputs.tag }}
          exclude: |
            .devcontainer/**/*
            .vscode/**/*
            lib/**/*
            scripts/**/*
            test/**/*
            docker-compose.yml
            buildimage.Dockerfile
            jest.config.js
            package.json
            tsconfig.json
            yarn.lock
